### Register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
	"username": "fotismenos007",
	"email": "fotismenos007@mail.ru",
	"password": "root123"
}

### Validation message: should return 401 with validation message
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
	"username": "",
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}

### LogIn user & get jwt access & refresh token
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"username": "fotismenos007",
	"password": "root123"
}

### Refresh token
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
	"refreshToken": "fe76c490-9f6f-4c1d-b166-8d9969728347"
}

### LogOut user
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiODY2NTA2NTUtM2JkNi00MTdhLWE3NzgtMzEwOThkYjNlYzZkIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzMzMjg0MDU3LCJleHAiOjE3MzMyODc2NTd9.g_A27WOMyMnrbdfohY0-YAgnoFiDsbrnNXKsjWTXu8MU1ZNnkUN09fHK8JNOgW8ISI3_r4QrjowFqRL64fjm9A
Content-Type: application/json

{
	"refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiODY2NTA2NTUtM2JkNi00MTdhLWE3NzgtMzEwOThkYjNlYzZkIiwiaWF0IjoxNzMzMjg0MDU3LCJleHAiOjE3MzM4ODg4NTd9.ApzOxMjZ2cu0iXtpEnogbeuXn0tqZWPmKTQPRaQ9G3c3yoQ2-kWA0Ct9OE0CpWiD4Va6jU4PkC6D72w95yOFhw"
}
