### Register user
### Return -> success ? "uuid" : "string message"
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
	"username": "fotismenos",
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}

### Validation message
### should return 401 with validation message
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
	"username": "",
	"email": "akbarjondev007@gmail.com",
	"password": "root123"
}
