### token for ADMIN login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"username": "akbar007",
	"password": "root123"
}

### token for USER login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"username": "fotismenos007",
	"password": "root123"
}

### Create
POST http://localhost:8080/api/v1/workoutplan
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiYzgyYjcxYTctOTA2Mi00OGI0LWJhOTQtNzBmZDAzNzhmNjljIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzM1NDg2ODYyLCJleHAiOjE3MzU0OTA0NjJ9.hU4kEZfp-l47e-AsgTqZieugFkydUuk85t16yNZ-1x6QmOTGkCGMcYizU2dIQoLpuEzKqz_7WyK3qgOJAFFKdg
Content-Type: application/json

{
	"scheduledDateTime": "2025-11-30T14:30:00.000+0500",
	"exerciseIds": [
		"242d3963-019c-4849-9761-c48bd51a6a38",
		"632e442c-4046-498c-a829-496a23524a1b",
		"8c1fd09a-7605-45d8-b4a8-0659793aae8e"
	]
}

### All users' workoutplans for only admins (pagination default page = 1 & size = 10)
GET http://localhost:8080/api/v1/workoutplan
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcjAwNyIsInVzZXJJZCI6ImU5OTEzMTlmLThmZTMtNDc1Zi1hYjYzLTliMjczYTRhNzUwMiIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifSx7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTczNTQ4Njc1OSwiZXhwIjoxNzM1NDkwMzU5fQ.M4nVfVuAIYz_UaRe7df4893yNOxLX7Eojw4HhdD09StP3B8zt0y0mWh4e2DDW8Zt20YMJaPPnLl0dkD0SOYT4Q

### User's all workoutplans (pagination default page = 1 & size = 10)
GET http://localhost:8080/api/v1/workoutplan/mine
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiYzgyYjcxYTctOTA2Mi00OGI0LWJhOTQtNzBmZDAzNzhmNjljIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzM1NDg2ODYyLCJleHAiOjE3MzU0OTA0NjJ9.hU4kEZfp-l47e-AsgTqZieugFkydUuk85t16yNZ-1x6QmOTGkCGMcYizU2dIQoLpuEzKqz_7WyK3qgOJAFFKdg

### Any workoutPlan by id for admin
GET http://localhost:8080/api/v1/workoutplan/8012d54e-a280-420c-a5b0-d9d69ca6369a
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcjAwNyIsInVzZXJJZCI6ImU5OTEzMTlmLThmZTMtNDc1Zi1hYjYzLTliMjczYTRhNzUwMiIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifSx7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTczNTk4MjkxNiwiZXhwIjoxNzM1OTg2NTE2fQ.EwKpGdgDwKD2aE1U4ceq3yolDdjtF2IcbngkyYfC8SjOxtOIpjgunbFky1g_gCz02Wii7pP-d7P5sc6OaR_W9Q

### user's workoutPlan by id
GET http://localhost:8080/api/v1/workoutplan/d2d97309-8f6f-4fe2-b187-b9e54201d8b9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiYzgyYjcxYTctOTA2Mi00OGI0LWJhOTQtNzBmZDAzNzhmNjljIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzM1OTgyOTQ3LCJleHAiOjE3MzU5ODY1NDd9.rMoSrXYlc6qHR_TpVWZOeLw38w1a6WZIcFnt4EmUf_pGIkfP4U6OwOtRKI7-EFOIdtsk-vH03Uq2AQizY2zgtQ

### Update
PUT http://localhost:8080/api/v1/workoutplan/d2d97309-8f6f-4fe2-b187-b9e54201d8b9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiYzgyYjcxYTctOTA2Mi00OGI0LWJhOTQtNzBmZDAzNzhmNjljIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzM2MTMwMTYxLCJleHAiOjE3MzYxMzM3NjF9.QfdNQ1J4TL8KjnL1Gq5_pz7DPOK_YvQ9mixSSw4VdZR5OsBiI1CkEwYv3JOTbWkdUPWfmWoeoE0fqVoqT1TeMQ
Content-Type: application/json

{
	"status": "PENDING",
	"scheduledDateTime": "2025-12-30T14:30:00.000+0500",
	"ownerId": "e991319f-8fe3-475f-ab63-9b273a4a7502",
	"exerciseIds": [
		"242d3963-019c-4849-9761-c48bd51a6a38",
		"632e442c-4046-498c-a829-496a23524a1b",
		"8c1fd09a-7605-45d8-b4a8-0659793aae8e"
	]
}
