### ADMIN login for tokens
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"username": "akbar007",
	"password": "root123"
}

### USER login for tokens
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
	"username": "fotismenos007",
	"password": "root123"
}

### Create
POST http://localhost:8080/api/v1/workoutplan
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcjAwNyIsInVzZXJJZCI6IjVhY2VhNjg1LTJjZGUtNDk1OS1iNjBlLTg3M2YwZGVhMDg2MiIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifSx7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTczMzQ3NjgzMCwiZXhwIjoxNzMzNDgwNDMwfQ.QCIOL7e0b2886mmnmXEttOQGhPc9ejpGO-aMmezyXA___Cz0KF6AroxUouIAV1L8SDEFb4wFXgNH8BXzAgoBCA
Content-Type: application/json

{
	"scheduledDateTime": "2025-11-30T14:30:00.000+0500",
	"exerciseIds": [
		"af096ea3-626f-4c70-a59d-44fa5d6b7c5c",
 		"31e40b2f-2ac6-48a0-8b0e-ad3c9030b53f",
 		"7d4e5cdd-0bcf-47d5-bb94-b3dd15bb1db4"
	]
}

### All users' workoutplans for only admins (pagination default page = 1 & size = 10)
GET http://localhost:8080/api/v1/workoutplan
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJha2JhcjAwNyIsInVzZXJJZCI6IjVhY2VhNjg1LTJjZGUtNDk1OS1iNjBlLTg3M2YwZGVhMDg2MiIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifSx7ImF1dGhvcml0eSI6IlJPTEVfQURNSU4ifV0sImlhdCI6MTczMzQ3OTQzNiwiZXhwIjoxNzMzNDgzMDM2fQ.mF7fkKlb5zTCkAiYOaOew06lE2qHr43yT2SSO-VKWTFMaZ5jz2b0WMwYE34LDqxunLQnM-OuBpEhtq2kPNvYdA

### User's all workoutplans (pagination default page = 1 & size = 10)
GET http://localhost:8080/api/v1/workoutplan/mine
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJmb3Rpc21lbm9zMDA3IiwidXNlcklkIjoiMjNmZjg0MjctNGE2My00YTBkLTgxMmUtNmYxZjkzYzE3ZDdiIiwiYXV0aG9yaXRpZXMiOlt7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiaWF0IjoxNzMzNDc5NTMyLCJleHAiOjE3MzM0ODMxMzJ9.-wxlG4-X-I6csCDm2egFFgrnyMJzLu81Cj9Avfrx-HDiDeyIkw9V7z9TLI0PzLqW1COdkuxPoHdC4WHBoR5PPw
